name: CustomDeathMessages
version: 1.6.2
main: me.element.customdeathmessages.CustomDeathMessages
description: Custom Death Messages made by Element_85
author: Element_85
api-version: 1.16

commands:
  cdm:
   aliases: customdeathmessages
   description: Command used for reloading.
   permission: cdm.reload
   
permissions: 
  cdm.reload:
   description: Permission used for reloading.
  cdm.updates:
   description: Permission used for sending update messages to ops.